#!/usr/bin/env python3
"""
Post a generated reel to Instagram, TikTok, and LinkedIn via Buffer GraphQL API.

Buffer requires the video to be at a public URL — this script uploads the
MP4 to a GitHub release first, then passes that URL to Buffer.

Usage:
    python post_to_buffer.py reels/<slug>
    python post_to_buffer.py reels/<slug> --schedule "2026-06-25T19:00:00+02:00"
    python post_to_buffer.py reels/<slug> --dry-run

Requires in .env:
    BUFFER_TOKEN             — Buffer API access token
    BUFFER_INSTAGRAM_ID      — Buffer channel ID for Instagram
    BUFFER_TIKTOK_ID         — Buffer channel ID for TikTok (optional)
    BUFFER_LINKEDIN_ID       — Buffer channel ID for LinkedIn (optional)
    GITHUB_REPO              — GitHub repo for hosting the video (e.g. org/repo)
"""

import argparse
import json
import os
import re
import sqlite3
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx
from dotenv import load_dotenv

SCRIPT_DIR = Path(__file__).resolve().parent

load_dotenv(SCRIPT_DIR / ".env", override=False)

BUFFER_GRAPHQL = "https://api.buffer.com/graphql"
TOKEN          = os.getenv("BUFFER_TOKEN")
IG_CHANNEL     = os.getenv("BUFFER_INSTAGRAM_ID")
TT_CHANNEL     = os.getenv("BUFFER_TIKTOK_ID")
LN_CHANNEL     = os.getenv("BUFFER_LINKEDIN_ID")

GITHUB_REPO    = os.getenv("GITHUB_REPO", "followthemoneyknowledge/followthemoney")
DB_PATH        = SCRIPT_DIR / "data" / "pipeline.db"


# ── Caption parser ─────────────────────────────────────────────────────────────

def _parse_captions(captions_md: str) -> dict[str, str]:
    """Extract caption text from the code block under each platform's ### Caption section."""
    def _extract(section_header: str) -> str:
        pattern = rf"{re.escape(section_header)}.*?###\s+Caption\s+```(.*?)```"
        m = re.search(pattern, captions_md, re.DOTALL | re.IGNORECASE)
        return m.group(1).strip() if m else ""

    return {
        "instagram": _extract("## 📸 Instagram"),
        "tiktok":    _extract("## 🎵 TikTok"),
        "linkedin":  _extract("## 💼 LinkedIn"),
    }


# ── GitHub release upload ──────────────────────────────────────────────────────

def _upload_to_github(
    video_path: Path,
    reel_slug: str,
    dry_run: bool,
    release_title: str | None = None,
) -> str | None:
    """Upload MP4 to a GitHub release. Returns the public video URL or None."""
    tag = f"reel-{reel_slug}"

    if dry_run:
        url = f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/reel.mp4"
        print(f"  [dry-run] would upload to GitHub release: {tag}")
        print(f"  [dry-run] video URL: {url}")
        return url

    print(f"  Creating GitHub release '{tag}'...")
    result = subprocess.run(
        [
            "gh", "release", "create", tag,
            str(video_path),
            "--repo",  GITHUB_REPO,
            "--title", release_title or f"Follow the Money — {reel_slug}",
            "--notes", "Auto-generated by Follow the Money reel pipeline",
        ],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        if "already exists" in result.stderr:
            print("  Release exists — uploading to existing release...")
            r2 = subprocess.run(
                ["gh", "release", "upload", tag, str(video_path),
                 "--repo", GITHUB_REPO, "--clobber"],
                capture_output=True, text=True,
            )
            if r2.returncode != 0:
                print(f"  ✗ GitHub upload failed: {r2.stderr[:200]}")
                return None
        else:
            print(f"  ✗ GitHub release failed: {result.stderr[:200]}")
            return None

    url = f"https://github.com/{GITHUB_REPO}/releases/download/{tag}/reel.mp4"
    print(f"  ✓ Uploaded — {url}")
    return url


# ── Buffer GraphQL ─────────────────────────────────────────────────────────────

_CREATE_POST = """
mutation CreatePost($input: CreatePostInput!) {
  createPost(input: $input) {
    ... on PostActionSuccess {
      post {
        id
        status
        dueAt
      }
    }
    ... on MutationError {
      message
    }
  }
}
"""


def _post_to_buffer(
    client: httpx.Client,
    channel_id: str,
    platform: str,
    text: str,
    video_url: str,
    scheduled_at: str | None,
    dry_run: bool,
) -> bool:
    if dry_run:
        ts = scheduled_at or "queue"
        print(f"  [dry-run] {platform}: channel={channel_id}, schedule={ts}")
        print(f"            {text[:120]}...")
        return True

    metadata: dict = {}
    if platform == "Instagram":
        metadata["instagram"] = {"type": "reel", "shouldShareToFeed": True}
    elif platform == "TikTok":
        metadata["tiktok"] = {"title": text[:150]}
    elif platform == "LinkedIn":
        metadata["linkedin"] = {}

    variables: dict = {
        "input": {
            "channelId":      channel_id,
            "text":           text,
            "assets":         [{"video": {"url": video_url}}],
            "schedulingType": "automatic",
            "metadata":       metadata,
        }
    }

    if scheduled_at:
        dt = datetime.fromisoformat(scheduled_at).astimezone(timezone.utc)
        variables["input"]["mode"]  = "customScheduled"
        variables["input"]["dueAt"] = dt.isoformat()
    else:
        variables["input"]["mode"] = "addToQueue"

    r = client.post(
        BUFFER_GRAPHQL,
        json={"query": _CREATE_POST, "variables": variables},
    )

    if r.status_code != 200:
        print(f"  ✗ {platform} HTTP {r.status_code}: {r.text[:300]}")
        return False

    data = r.json()
    if data.get("errors"):
        print(f"  ✗ {platform} GraphQL error: {data['errors'][0].get('message')}")
        return False

    result = data.get("data", {}).get("createPost", {})
    if "message" in result:
        print(f"  ✗ {platform} Buffer error: {result['message']}")
        print(f"      Full response: {json.dumps(data)[:400]}")
        return False

    post = result.get("post")
    if not post:
        print(f"  ✗ {platform} unexpected response: {json.dumps(data)[:400]}")
        return False

    print(f"  ✓ {platform} — id: {post.get('id')}  status: {post.get('status')}  due: {post.get('dueAt', 'queue')}")
    return True


# ── DB recording ───────────────────────────────────────────────────────────────

def _record_posted_buffer(reel_slug: str, platforms: list[str]) -> None:
    """Record which platforms the reel was posted to in pipeline.db."""
    if not DB_PATH.exists():
        return
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS buffer_posts (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            reel_slug   TEXT NOT NULL,
            platforms   TEXT,
            posted_at   TEXT DEFAULT (datetime('now'))
        )
    """)
    conn.execute(
        "INSERT INTO buffer_posts (reel_slug, platforms) VALUES (?, ?)",
        (reel_slug, ",".join(platforms)),
    )
    conn.commit()
    conn.close()


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Post a Follow the Money reel to Buffer")
    parser.add_argument("reel_dir",        help="Reel folder path (e.g. reels/ftm-fifa-2026-06-21)")
    parser.add_argument("--schedule",      default=None,
                        help="ISO 8601 datetime, e.g. 2026-06-25T19:00:00+02:00")
    parser.add_argument("--no-instagram",  dest="instagram", action="store_false", default=True)
    parser.add_argument("--no-tiktok",     dest="tiktok",    action="store_false", default=True)
    parser.add_argument("--no-linkedin",   dest="linkedin",  action="store_false", default=True)
    parser.add_argument("--dry-run",       action="store_true")
    args = parser.parse_args()

    reel_dir      = SCRIPT_DIR / args.reel_dir
    video_path    = reel_dir / "output" / "reel.mp4"
    captions_path = reel_dir / "output" / "captions.md"
    reel_slug     = reel_dir.name

    if not reel_dir.exists():
        print(f"✗ Reel folder not found: {reel_dir}")
        sys.exit(1)
    if not video_path.exists():
        print(f"✗ No reel.mp4 found — run make_reel.py first:")
        print(f"    python reel_template/make_reel.py {args.reel_dir}")
        sys.exit(1)
    if not captions_path.exists():
        print(f"✗ No captions.md found — run make_captions.py first:")
        print(f"    python reel_template/make_captions.py {args.reel_dir}")
        sys.exit(1)
    if not args.dry_run and not TOKEN:
        print("✗ BUFFER_TOKEN not set in .env")
        sys.exit(1)

    # Parse org name from reel_config.py for the release title
    org = reel_slug
    config_path = reel_dir / "reel_config.py"
    if config_path.exists():
        m = re.search(r'"location_name"\s*:\s*"([^"]+)"', config_path.read_text())
        if m:
            org = m.group(1).title()

    captions = _parse_captions(captions_path.read_text())

    print("═" * 62)
    print("  BUFFER POSTER — Follow the Money")
    print(f"  Reel:  {reel_slug}")
    print(f"  Org:   {org}")
    print(f"  Mode:  {'DRY RUN' if args.dry_run else 'LIVE'}")
    print(f"  Sched: {args.schedule or 'add to queue'}")
    print("═" * 62)

    # Step 1 — host video on GitHub
    print("\n▸ Hosting video on GitHub releases...")
    video_url = _upload_to_github(
        video_path, reel_slug, args.dry_run,
        release_title=f"Follow the Money — {org} ({datetime.now().strftime('%Y-%m-%d')})",
    )
    if not video_url:
        sys.exit(1)

    # Step 2 — post to Buffer
    print("\n▸ Posting to Buffer...")
    headers = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
    results = []

    with httpx.Client(headers=headers, timeout=30) as client:
        if args.instagram and (IG_CHANNEL or args.dry_run):
            ok = _post_to_buffer(client, IG_CHANNEL or "IG_ID", "Instagram",
                                 captions["instagram"], video_url, args.schedule, args.dry_run)
            results.append(("Instagram", ok))
        elif args.instagram:
            print("  ⚠ BUFFER_INSTAGRAM_ID not set — skipping")

        if args.tiktok and (TT_CHANNEL or args.dry_run):
            ok = _post_to_buffer(client, TT_CHANNEL or "TT_ID", "TikTok",
                                 captions["tiktok"], video_url, args.schedule, args.dry_run)
            results.append(("TikTok", ok))
        elif args.tiktok and not TT_CHANNEL:
            print("  ⚠ BUFFER_TIKTOK_ID not set — skipping")

        if args.linkedin and (LN_CHANNEL or args.dry_run) and captions.get("linkedin"):
            ok = _post_to_buffer(client, LN_CHANNEL or "LN_ID", "LinkedIn",
                                 captions["linkedin"], video_url, args.schedule, args.dry_run)
            results.append(("LinkedIn", ok))
        elif args.linkedin and not LN_CHANNEL:
            print("  ⚠ BUFFER_LINKEDIN_ID not set — skipping")

    print("\n" + "═" * 62)
    for platform, ok in results:
        mark = "✓" if ok else "✗"
        print(f"  {mark} {platform}")
    print("═" * 62)

    posted_platforms = [p for p, ok in results if ok]
    if posted_platforms and not args.dry_run:
        _record_posted_buffer(reel_slug, posted_platforms)
        print(f"\n  Recorded in pipeline.db: {', '.join(posted_platforms)}")


if __name__ == "__main__":
    main()
